- jaidedread/jaidedread.py
- jaidedread/utils.py
I add `encoding` to open file. Prevent problems when using with Windows.
> Add encoding

- easyocr/detection.py
- easyocr/easyocr.py
- easyocr/utils.py
I have added functions to read text from byte object
I did not want to change any original function so just created new functions for this 
#27 PR for this issue
> Read text from images

- README.md
- easyocr/easyocr.py
This PR checks if the file downloaded correctly or not. If the downloaded file is corrupted or not fully download the file will be deleted and a redownload will be initiated.
> Add md5 verification for downloaded models

- easyocr/character/az_char.txt
Adding: Missing Azerbaijani characters
- Ç, Ə, İ, Ş, ə, ğ, ş
> add az characters

- easyocr/easyocr.py
I already test that it really works this time.
>  Allow loading URL in .readtext(url), issue #86

- setup.py
1. Changed **`install_requires = requirements`** by reading from `requirements.txt` file without custom typing.
2. Added **`long_description = readme()`** by reading `README.md` file.
1. Prevents custom typing of all the packages inside **`install_requires`** . Rather, It reads from the `requirements.txt` file
2. **`long_description`** enables suitability of display in pypi package launch by reading it from `README.md file`.
Stable ✔️
@rkcosmos
> Modified setup.py for ease of installation with requirements.txt automatically

- easyocr/easyocr.py
- easyocr/utils.py
Thank you for great project!
I'm using this project on Python2.7, and for python2.7, I change several part to live both with python2 and python3.
> support for python2.7

- Dockerfile
Added in a Dockerfile for this, worked on something very similar and have a lot of features and tests in my repo. Would be great to collaborate. I'll add the container into my dockerhub
> Added Dockerfile env, ready to publish to dockerhub

- easyocr/easyocr.py
Support user path via os.path.expanduser().
> Make readtext() can use '~' path

- easyocr/easyocr.py
- easyocr/utils.py
Adds progres bar into "Downloading recognition model, please wait. This may take several minutes depending upon your network connection." and to other "urlretrieve" calls
> add progress bar to urlretrieves

- easyocr/recognition.py
No need to reshape the tensor twice
> Duplicated view operation doesn't have any effect

- easyocr/easyocr.py
- easyocr/utils.py
This PR is about issue #307 .
Users can use easyocr with rotation information as much as they know about the image.
for example,
`result = reader.readtext(img, rotation_info=[90,180,270])`
> manage rotated (90,180,270) text

- easyocr/easyocr.py
thank you for your bug report. I fixed it
> fix ZeroDivision Error for blank images #346

- easyocr/utils.py
It seems that height is default parameter for setting box margin on the assumption that height would be smaller than width.
I fixed it to compare between width and height.
> Update margin method

- easyocr/detection.py
PR related to issue #474 
There was a delay in inference on GPU mode with the new detection code causing inference to be significantly slower in release 1.4 compared to 1.3.2
This should hopefully fix the speed issue by changing some code in the preprocessing steps.
> Fix detection speed issue

- README.md
The current link does not work.
> Fix: broken link for Train/use your own model

- README.md
- custom_model.md
A PR to fix typo and grammar errors in the README.md and custom_model.md
> Fix a variety of typos and grammar errors

- easyocr/utils.py
This is just implementing the solution proposed in the issue. Testing against some of my own documents with this problem showed the solution is working as expected.
> Fixes JaidedAI/EasyOCR#504

- requirements.txt
> downgrade to opencv nov 2021 version to avoid core dump 

- README.md
added link for web demo on Hugging Face Spaces using Gradio by https://huggingface.co/tomofi
> add web demo link on Hugging Face Spaces

- README.md
Install from GitHub URL not Working properly. Corrected the working code.
> Updated README,md

- easyocr/DBNet/DBNet.py
- easyocr/DBNet/README.md
- easyocr/detection_db.py
- easyocr/scripts/compile_dbnet_dcn.py
> fix windows path

- easyocr/model/modules.py
- trainer/craft/model/vgg16_bn.py
fix torchvision<0.13 backward compatibility
> fix torchvision<0.13 backward compatibility

- easyocr/cli.py
- easyocr/easyocr.py
for #732 .
Add the choice json to the output_format argument.
No API changes.
> JSON output

- easyocr/config.py
altered the tamil characters for optical character recognition in other languages
> Updated config.py

- easyocr/easyocr.py
Added support for Apple Silicon.
All kudos to @rayeesoft , see https://github.com/JaidedAI/EasyOCR/issues/806#issuecomment-1366326769
> Added support for Apple Silicon

- easyocr/utils.py
replaced Image.ANTIALIAS with Image.Resampling.LANCZOS due to ANTIALIAS being deprecated and removed in Pillow 10
> replaced Image.ANTIALIAS with Image.Resampling.LANCZOS
