easyocr/easyocr.py
Hi, thanks for sharing this library. It seems to work well and is very easy to use indeed.
One minor issue is that if you import it on a computer with no GPU without manually specifying `gpu=False`, it will crash with a non-obvious error:
```python
>>> reader = easyocr.Reader(['en'])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/easyocr/easyocr.py", line 166, in __init__
self.detector = get_detector(DETECTOR_PATH, self.device)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/easyocr/detection.py", line 61, in get_detector
net.load_state_dict(copyStateDict(torch.load(trained_model, map_location=device)))
File …
```
=> Updating GPU detection logic to support CPU-only computers

easyocr/easyocr.py
Set default MODULE_PATH to "~/.EasyOCR/" to avoid run as root. User can also use "MODULE_PATH" environment variable to set MODULE_PATH.
=> Set MODULE_PATH to home to avoid run as root

easyocr/detection.py
Without this, I got the following error message when trying to run it with GPU:
```
module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
```
=> Fix missing to(device) for DataParallel in detection.py

setup.py
I'm using this project on Python2.7.
In Python2.7, 'encoding' is an invalid keyword argument for the default `oepn` function.
=> Compatible with python 2.7

easyocr/easyocr.py, easyocr/utils.py
Hi,
I saw your post on HackerNews a while back and had a chance to play with the EasyOCR package today. These are some minor updates that enable use of the EasyOCR module in certain production setups that I wanted to contribute back to you.
* Use Python logger instead of printing to STDERR. This allows logger statements to be managed and flow according to whatever logging configuration is needed by the application. For example, some production systems will use a JSON-formatted logger setup. Printing directly to STDERR can either cause the errors to be lost or be non-parseable by these types of production setups.
* Adds two optional arguments to init(): model_storage_directory and download_enabled. I have implemented these as fully backwards-compatible with your prior logic.
* When …
=> Minor updates to support production use cases

easyocr/craft_utils.py
There is a small typo in easyocr/craft_utils.py.
Should read `width` rather than `widh`.
=> docs: Fix simple typo, widh -> width

easyocr/craft_utils.py, easyocr/detection.py, easyocr/easyocr.py, easyocr/utils.py
This PR introduces the ability to estimate the number of characters in each textbox, first mentioned in Issue #311 .  It adds the optional argument `optimal_num_chars` to the `detect` function, which represents the optimal number of characters in each text box.
The output of the `detect` function remains a list of text boxes. However, if for example a user is looking for a 10-digit serial number, setting `optimal_num_chars=10` will estimate the number of characters in each text box, and sort the output such that text boxes with around 10 characters are put first. This way, when the user loops through this list calling `predict` on each textbox, they are able to find the desired e.g. serial number quickly.
As I mentioned in the issue, I found this useful in my case - happy to make any …
=> Estimate number of characters in textbox

easyocr/utils.py
Fix bug group_text_box(...) when a y_center of the big boxes almost equal to a y_center of the smaller boxes.
In my example, after running over "horizontal_list = sorted(horizontal_list, key=lambda item: item[4])", a big box will be arranged in the middle of the small boxes, their y_center are nearly equal. Next, when we group them by compare height_ths and ycenter_ths, the big box will separate the small boxes into parts instead of one, the small boxes will be split further after checking with width_ths.
I think, we should to checking height_ths after group it the lines by y_center, do sort again, then checking height_ths and widthd_ths. This will stop a big box separate a same y_center group of the small box , whereas the big box is not really in between them
This is a sample image …
=> Fix bug group text box when a y_center of the big boxes almost equal to a y_center of the smaller boxes.

easyocr/easyocr.py, easyocr/utils.py
This allows users to hide the progress-bar when executing the code.
In automatic builds using docker, the logs get polluted by the progress-bar (it is printed again and again at each step as it doesn't do an update).
The class `Reader` gains a new parameter `verbose` which is passed to the `utils.download_and_unzip` function.
=> Feature: Add `verbose` parameter to `Reader` class to hide download progressbar

easyocr/recognition.py, easyocr/utils.py
- MUCH faster greedy decoding function: 20-1000x (+) speedup, which in turn, speeds up the whole ocr process by 1.1-2x. The bigger the text the bigger the speedup. The difference is noticeable when scanning multiple images. One of my scans used to take ~2700s with 900s greedy decoding time. Now, the decoding part takes 1.5s (Added some comments to explain the vectorization process). On a side note, I'm not sure why there is a `for` loop for the elements of the `length` tensor (arg in `decode_greedy`), since in my testing, the tensor always had 1 element.
- Support for 3D grayscale arrays (MxNx1) .
=> Faster greedy decoding and support for 3D grayscale

easyocr/easyocr.py
Yes again x) But this time I just add an argument and the api will remain unchanged
=> Dict output 2

.gitignore, .vscode/settings.json, easyocr/utils.py
Hi there, This PR resolves issue #382. @miliadis and I worked together and successfully resolved this issue by having the aspect ratio and resize method adapt when width > height and height > width. Currently the cropped regions in `horizontal_list` and `free_list` are resized so the height fits the `model_height`([L523](https://github.com/JaidedAI/EasyOCR/blob/2e94e151ba00540f633d7a6cb595c99a7e74dbab/easyocr/utils.py#L523) and [L543](https://github.com/JaidedAI/EasyOCR/blob/2e94e151ba00540f633d7a6cb595c99a7e74dbab/easyocr/utils.py#L543)).
The image resizing is calculated by computing the aspect ratio, which is width/height ([L522](https://github.com/JaidedAI/EasyOCR/blob/2e94e151ba00540f633d7a6cb595c99a7e74dbab/easyocr/utils.py#L522) and …
=> Vertical Text Support

easyocr/export.py
Adding onnx export for craft text detector. Not adding the onnx converter for recognizer since there are still some problems with the conversion.
Instructions for onnx export:
```bash
$ git clone https://github.com/JaidedAI/EasyOCR
$ cd EasyOCR                                     # cd into EasyOCR repo
$ pip install -r requirements.txt                # install requirements for easyOCR inside a virtual env
$ pip install onnx==1.9.0 onnxruntime==1.8.0
$ python -m easyocr.export --dynamic             # export craft detector as onnx with recommended dynamic flag for dynamic input shape [bsize, 3, height, width] and for english language detection and recognition
```
To get help on other export options
```bash
$ python -m easyocr.export -h                    
$ python -m easyocr.export -l en …
```
=> Add craft detector onnx export

easyocr/export.py
Fixed issue where easyocr detector was being loaded in gpu by default before onnx export.
onnx export does not work with the model in data parallel mode so the model must be exported to onnx in CPU mode even when gpus are avai.
=> Fix onnx export issue when gpu is avai

requirements.txt
Replace `opencv-python` in `requirements.txt` with headless version for smooth deployment in servers and containers.
See also issue #485.
=> Using opencv-python-headless in requirements.txt

easyocr/easyocr.py, trainer/train.py, trainer/trainer.ipynb
`train.py`  and `trainer.ipynb`:
When training the recognition model on Arabic text I would get an error when reading the config file as well as displaying and saving the logs.
`easyocr.py`  :
When I loaded user defined model I would get an error when reading recog_network.yaml due to having Arabic character in there. 
So I added utf8 encoding when: 
- Reading the config file during training **inside** `trainer.ipynb`
- Displaying and Saving the logs **inside** `train.py`
- Reading user defined mode **inside** `easyocr.py`
=> Encoding: Added utf-8 encoding in 3 files

easyocr/easyocr.py, easyocr/utils.py
I believe the prior implementation of `set_result_with_confidence` doesn't do what the docs say with regards to the `rotation_info` kwarg
> Allow EasyOCR to rotate each text box and return the one with the best confident score.
In fact it seems to be simply selecting the longest string, not the most confident. See this line: https://github.com/JaidedAI/EasyOCR/blob/c471b1ce1ceb0aba3cb59463083c7e6f8a86b098/easyocr/utils.py#L802
So this PR addresses that, ie I rewrote `set_result_with_confidence` to indeed select the result with the highest confidence.
Happy for maintainers to edit my PR. Just note that the prior version has a check on whether a result exists (see that line I linked above - `if result_to_split[rot]`). I dropped this because I couldn't see why it was necessary - but feel …
=> Fix rotation tta best result selection

easyocr/easyocr.py
When using a custom model, there is a bug that uses the "imgH" value at config.py. It has been modified to use variables in the yaml file. (Using global variables)
=> Fix: Using Variables(imgH) for Custom Models

easyocr/easyocr.py
`setModelLanguage` accepts string expression of `list` as a `list_lang_string`. But when using user-defined model it passes a list to method directly. This cause that the Python interpreter can not reveal what is really wrong, showing TypeError.
And is there any reason that not using `str()` for `list_lang_string` of `setModelLanguage`? I think `list_lang_string` can be derived from `str(list_lang)`
=> Fix wrong parameter type for `setModelLanguage`

trainer/craft/metrics/eval_det_iou.py, trainer/craft/utils/inference_boxes.py, trainer/modules/transformation.py, trainer/test.py
There are small typos in:
- trainer/craft/metrics/eval_det_iou.py
- trainer/craft/utils/inference_boxes.py
- trainer/modules/transformation.py
- trainer/test.py
Fixes:
- Should read `multiplying` rather than `multipling`.
- Should read `matrices` rather than `matrixs`.
- Should read `decoder` rather than `deocder`.
- Should read `choose` rather than `choise`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

easyocr/easyocr.py
It appeared that when using a custom model, language symbol list is made from language characters and explicitly stated **symbol** string, so all symbols that are not listed in **symbol** string are being put to **ignore_char**. 
This led to the problem, that adding some special characters as © (copyright sign) to the custom model config file resulted in skipping this character on evaluation and excluding images with this character from the data loader on train.
That is why a possibility for a custom model to use **character_list** from its config file instead of predefined list of symbols was added.
=> Feature: Use non-listed symbols for custom model

easyocr/model/modules.py, easyocr/model/vgg_model.py, easyocr/recognition.py, trainer/craft/model/vgg16_bn.py
The model class definitions had minor issues that prevented compilation with `torch.jit.script`:
* `vgg16_bn` used `namedtuple` in `forward`
* No features of `namedtuple` were actually being used, so now returns a regular tuple
* `BidirectionLSTM` used a `try`/`except` in `forward`
* Instead of try/except there, added a method override in `get_recognizer` when GPU is enabled to inject the `rnn.flatten_parameters()` call
* `torch.jit.script` does not support `nn.AdaptiveAvgPool2d` with `None` dims
* Replaced with `torch.mean(x, dim=3)`, which is equivalent at the relevant line
Other edits are just import ordering / dead import removes, line breaks, etc.
Using `torch.jit.script` and `torch.jit.optimize_for_inference` allowed me to run models about 14% faster on CPU in …
=> Modify model classes to allow serialization and optimization with TorchScript

easyocr/model/modules.py, trainer/craft/model/vgg16_bn.py
Updating the `pretrained` parameter to remove the UserWarnings from PyTorch as discussed in https://github.com/JaidedAI/EasyOCR/issues/766. That fixed the warnings for the example that was provided, and there were no other use of that parameter when I grepped in the repo.
=> Update deprecated pretrained parameter

setup.cfg
When building the project via `python setup.py build`, I get this warning from `dist.py`:
```sh
/usr/lib/python3.10/site-packages/setuptools/dist.py:757: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
```
This patch changes `description-file` to `description_file`, fixing that warning.
=> Fix setuptools warning in setup.cfg

easyocr/DBNet/DBNet.py
Alias np.int has been deprecated and will result in an error: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
=> Fix DBNet for numpy >= 1.20.0

Dockerfile
Allows the container to be built with e.g. podman without additional configuration.
=> Dockerfile: Specify container registry

easyocr/easyocr.py
When using paragraph mode, I can't use `dict` or `json` output format because `get_paragraph` removes confidence information, hence the error
example:
```py
detections = ocr.readtext(image, output_format="dict", paragraph=True, slope_ths=0.3, text_threshold=0.5, width_ths=1)
```
this fix removes confidence if paragraph mode is being used.
=> fix: remove confidence if using paragraph mode

easyocr/easyocr.py
Fix get display import "from bidi import get_display" and no longer from "bidi.algorithm import get_display" this PR aim to fix that issue.
=> Fix: import get_display
